# Generated by Django 6.1.1 on 2026-09-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
