# Generated by Django 6.1.1 on 2026-09-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='adhesive',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('removable', 'Removable'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('none', 'Not Applicable')], default='permanent', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(choices=[('gloss', 'Gloss'), ('matte', 'Matte'), ('satin', 'Satin'), ('clear', 'Clear'), ('other', 'Other')], default='gloss', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(choices=[('vinyl', 'Vinyl'), ('paper', 'Paper'), ('mylar', 'Mylar'), ('polystyrene', 'Polystyrene'), ('other', 'Other')], default='vinyl', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='printing_method',
            field=models.CharField(choices=[('full_color', 'Full Color'), ('black_white', 'Black & White'), ('single_sided', 'Single-Sided'), ('double_sided', 'Double-Sided'), ('digital', 'Digital Printing'), ('screen', 'Screen Printing')], default='full_color', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('square', 'Square'), ('circle', 'Circle'), ('oval', 'Oval'), ('die_cut', 'Custom Die-cut')], default='rectangle', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('waste', 'Waste Companies'), ('government', 'Government Contractors'), ('motor', 'Motor & Car Companies'), ('pool', 'Pool Companies'), ('general', 'General Printing')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
