# Generated by Django 6.1.1 on 2026-09-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_adhesive_product_finish_product_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('waste_fleet_decals', 'Waste Company Fleet Decals'), ('dumpster_labels', 'Dumpster Identification Labels'), ('waste_safety_stickers', 'Waste Bin Safety Stickers'), ('waste_door_decals', 'Waste Service Door Decals'), ('government_site_labels', 'Government Project Site Labels'), ('contractor_vehicle_decals', 'Contractor Vehicle Decals'), ('equipment_compliance', 'Equipment Compliance Stickers'), ('project_asset_labels', 'Project Asset Number Labels'), ('auto_shop_decals', 'Auto Shop Logo Decals'), ('vehicle_window_stickers', 'Vehicle Window Stickers'), ('fleet_truck_graphics', 'Fleet Truck Graphics'), ('automotive_product_labels', 'Automotive Product Labels'), ('pool_truck_decals', 'Pool Service Truck Decals'), ('pool_equipment_labels', 'Pool Equipment Labels'), ('pool_chemical_stickers', 'Pool Chemical Safety Stickers'), ('other', 'Other / New Product')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='adhesive',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('removable', 'Removable'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('not_applicable', 'Not Applicable')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('waste', 'Waste Companies'), ('government', 'Government Contractors'), ('motor', 'Motor & Car Companies'), ('pool', 'Pool Companies'), ('other', 'Other Businesses')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, choices=[('gloss', 'Gloss'), ('matte', 'Matte'), ('satin', 'Satin'), ('clear', 'Clear'), ('other', 'Other / Specify in Notes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, choices=[('vinyl', 'Vinyl'), ('paper', 'Paper'), ('mylar', 'Mylar'), ('polystyrene', 'Polystyrene'), ('other', 'Other / Specify in Notes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='printing_method',
            field=models.CharField(blank=True, choices=[('full_color', 'Full Color'), ('black_white', 'Black & White'), ('single_sided', 'Single-Sided'), ('double_sided', 'Double-Sided'), ('digital', 'Digital Printing'), ('screen', 'Screen Printing')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('square', 'Square'), ('circle', 'Circle'), ('oval', 'Oval'), ('custom', 'Custom / Die-cut')], max_length=100),
        ),
    ]
