# Generated by Django 6.1.1 on 2026-10-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bag_tag', 'Bag & Tag Stickers'), ('container', 'Container & Dumpster Decals'), ('baler', 'Baler Decals'), ('compactor', 'Compactor Decals'), ('rolloff', 'Rolloff Decals'), ('recycling', 'Recycling Labels'), ('truck_fleet', 'Truck & Fleet Decals'), ('yard_waste', 'Yard Waste Decals'), ('safety', 'Safety & Compliance'), ('reflective', 'Reflective Products'), ('facility', 'Facility Signage'), ('food_waste', 'Food Waste Labels'), ('medical_waste', 'Medical Waste Labels'), ('portable_toilet', 'Portable Toilet Decals'), ('custom', 'Custom Labels'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('bag_tag', 'Bag & Tag Sticker'), ('container_decal', 'Container Identification Decal'), ('dumpster_decal', 'Dumpster Identification Decal'), ('baler_decal', 'Baler Decal'), ('compactor_decal', 'Compactor Decal'), ('rolloff_decal', 'Rolloff Decal'), ('recycling_label', 'Recycling Label'), ('truck_decal', 'Truck Decal'), ('fleet_decal', 'Fleet Decal'), ('yard_waste_label', 'Yard Waste Label'), ('safety_decal', 'Safety & Compliance Decal'), ('reflective_label', 'Reflective Label'), ('facility_sign', 'Facility Sign'), ('food_waste_label', 'Food Waste Label'), ('medical_waste_label', 'Medical Waste Label'), ('portable_toilet_decal', 'Portable Toilet Decal'), ('custom_label', 'Custom Label'), ('other', 'Other / New Product')], default='other', max_length=100),
        ),
    ]
