# Generated by Django 6.1.1 on 2026-10-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='industry',
            field=models.CharField(choices=[('waste', 'Waste Companies'), ('government', 'Government Contractors'), ('construction', 'Construction Companies'), ('motor', 'Motor Manufacturers'), ('trucking', 'Trucking Companies'), ('pool', 'Pool Companies'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
