# Generated by Django 6.1.1 on 2026-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('decals', 'Decals'), ('stickers', 'Stickers'), ('reflective', 'Reflective Products'), ('custom', 'Custom Products'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='industry',
            field=models.CharField(choices=[('truck_motor_car', 'Truck / Motor / Car Decals'), ('government', 'Government Contractor Decals'), ('pool', 'Pool Decals'), ('construction', 'Construction Decals'), ('waste', 'Waste Company Decals')], default='waste', max_length=100),
        ),
    ]
