# Generated by Django 6.1.1 on 2026-10-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_quoterequest_alter_orderitem_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCalendarStickerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_year', models.PositiveIntegerField(choices=[(2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050'), (2051, '2051'), (2052, '2052'), (2053, '2053'), (2054, '2054'), (2055, '2055'), (2056, '2056'), (2057, '2057'), (2058, '2058'), (2059, '2059'), (2060, '2060'), (2061, '2061'), (2062, '2062'), (2063, '2063'), (2064, '2064'), (2065, '2065'), (2066, '2066'), (2067, '2067'), (2068, '2068'), (2069, '2069'), (2070, '2070'), (2071, '2071'), (2072, '2072'), (2073, '2073'), (2074, '2074'), (2075, '2075'), (2076, '2076'), (2077, '2077'), (2078, '2078'), (2079, '2079'), (2080, '2080'), (2081, '2081'), (2082, '2082'), (2083, '2083'), (2084, '2084'), (2085, '2085'), (2086, '2086'), (2087, '2087'), (2088, '2088'), (2089, '2089'), (2090, '2090'), (2091, '2091'), (2092, '2092'), (2093, '2093'), (2094, '2094'), (2095, '2095'), (2096, '2096'), (2097, '2097'), (2098, '2098'), (2099, '2099'), (2100, '2100')])),
                ('trash_collection_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
                ('trash_collection_frequency', models.CharField(choices=[('Once per week', 'Once per week'), ('Every other week', 'Every other week'), ('Once per month', 'Once per month'), ('Other', 'Other')], max_length=50)),
                ('other_trash_frequency', models.CharField(blank=True, max_length=255)),
                ('recycling_collection_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
                ('recycling_collection_frequency', models.CharField(choices=[('Once per week', 'Once per week'), ('Every other week', 'Every other week'), ('Once per month', 'Once per month'), ('Other', 'Other')], max_length=50)),
                ('other_recycling_frequency', models.CharField(blank=True, max_length=255)),
                ('new_years_day', models.BooleanField(default=False)),
                ('memorial_day', models.BooleanField(default=False)),
                ('independence_day', models.BooleanField(default=False)),
                ('labor_day', models.BooleanField(default=False)),
                ('thanksgiving_day', models.BooleanField(default=False)),
                ('christmas_day', models.BooleanField(default=False)),
                ('other_holiday_1', models.CharField(blank=True, max_length=255)),
                ('other_holiday_2', models.CharField(blank=True, max_length=255)),
                ('other_holiday_3', models.CharField(blank=True, max_length=255)),
                ('top_bar_color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange')], max_length=20)),
                ('include_company_logo', models.BooleanField(default=False)),
                ('other_collection_information', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=255)),
                ('address_contd', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=30)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
