# Generated by Django 6.1.1 on 2026-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_collectioncalendarstickerorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="THE LABEL GROUP", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="INDUSTRIAL PRINTS & DECALS", max_length=255
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("whatsapp", models.CharField(blank=True, default="", max_length=100)),
                ("facebook", models.URLField(blank=True, default="")),
                ("instagram", models.URLField(blank=True, default="")),
                ("tiktok", models.URLField(blank=True, default="")),
                ("linkedin", models.URLField(blank=True, default="")),
                ("youtube", models.URLField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
